name: shell commands

on: push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: version script
        run: |
          node -v
      - name: Python commands
        run: |
          import platform
          print(platform.processor())
        shell: python